<?php
class Product
{
    protected $name;//Galaxy
    protected $price;
    protected $description;//телефон Модель телефона'
    protected $brand;//samsunc
    public function __construct($nam, $pr, $des, $br)
    {
        $this->name = $nam;//передали значения в переменные
        $this->price = $pr;
        $this->description = $des;
        $this->brand = $br;
    }
    public function getProduct()
    {
        return $this->description.''.$this->brand."".$this->name;
    }
}
class Phone extends Product
{
    private $cpu;
    private $ram;
    private $countSim;
    private $hdd;
    private $os;
                                //вызываем конструктор родителя + наследник
    public function __construct($nam, $pr, $des, $br,  $cpu, $ram, $sim, $hdd, $os)
    {
        parent::__construct($nam, $pr, $des, $br);//вызываем конструктор родителя
        $this->cpu = $cpu;//передали значения в переменные
        $this->ram = $ram;
        $this->countSim = $sim;
        $this->hdd = $hdd;
        $this->os = $os ;
    }
    public function getProducts()//вызываем return родителя
    {
        return parent::getProduct(); // TODO: Change the autogenerated stub
    }
    public function getParent()
    {
        return 'Экран :'.$this->cpu.'<br>Обьём памяти :' .$this->ram.'<br>Симкарты '.$this->countSim.
            '<br>Встроенная память :'.$this->hdd.'<br>Операционная система : '.$this->os;
    }

}
class Monitor extends Product
{
    private $diagonal;
    private $frequency;
    private $ports;
                        //вызываем конструктор родителя + наследник
    function __construct($nam, $pr, $des, $br,  $d, $freq, $ports)
    {
        parent::__construct($nam, $pr, $des, $br);//вызываем конструктор родителя
        $this->diagonal = $d;//передали значения в переменные
        $this->frequency = $freq;
        $this->ports = $ports;
    }
    public function getProd()//вызываем return родителя
    {//ненужен так как echo $rez1->getMonitor(); мы  не выводим ->getProd()
        return parent::getProduct(); // TODO: Change the autogenerated stub
    }
    public function getMonitor()
    {
        return '<br>Диагональ экрана :'.$this->diagonal."<br>Частота : ".$this->frequency."<br>Порт : ".$this->ports;
    }
}
$rez = new Product(' Galaxy', '', 'Модель телефона', ' Samsung');
//echo $rez->getProduct().'  вывело родителя'.'<br>';
echo '<pre>';
print_r($rez->getProduct());
echo '</pre>';
$rez2 = new Phone('Galaxy', '', 'Модель телефона', ' Samsung', 'Тачскрин', '8 ГБ', '2','128ГБ', 'Андроид' );
echo $rez2->getProducts().'<br>'.$rez2->getParent();
$rez1 = new Monitor('Galaxy', '', 'Модель телефона', ' Samsung','165,5 mm', '1.9ГГЦ', 'USB 3.16');
echo $rez1->getMonitor();

//вывела массив;
$rez3 =[$rez2->getProducts(),$rez2->getParent(),$rez1->getMonitor()] ;
echo '<pre>';
print_r($rez3);
echo '</pre>';
//вывела массив;
$arr = [$rez2, $rez1];

echo '<pre>';
print_r($arr);
echo '</pre>';









